version: "3.7"

services:
  dvd_store_web:

    build: .

    env_file:
      - .env-vars

    networks:
      - app-net

    depends_on:
      - db

    container_name: "dvd_store_web"


  db:
    image: db_dvd_store

    ports:
      - "3306:3306"

    env_file:
      - .env-vars

    volumes:
      - mysql_volume:/var/lib/mysql

    networks:
      - app-net

    container_name: "dvd_store_db"


  nginx:
    # location of nginx's Dockerfile
    build: ./project_config/nginx

    volumes:
      - ./staticfiles:/var/www/dvd_store/static/

    depends_on:
      - "dvd_store_web"

    networks:
      - app-net

    container_name: "dvd_store_nginx"

volumes:
  mysql_volume:
    external: true

networks:
  app-net:
    external:
      name: nat

