version: "3.7"

services:
  dvd_store_web:

    build: .

    env_file:
      - .env-vars

    networks:
      - cloudflare-net

    depends_on:
      - db
       
    restart: unless-stopped
    
    container_name: "dvd_store_web"


  db:
    image: capiedrav/db_dvd_store:v1

    ports:
      - "3306:3306"

    env_file:
      - .env-vars

    volumes:
      - db_dvd_store_volume:/var/lib/mysql

    networks:
      - cloudflare-net


    restart: unless-stopped

    container_name: "dvd_store_db"


  nginx:
    # location of nginx's Dockerfile
    build: ./project_config/nginx

    volumes:
      - ./staticfiles:/var/www/dvd_store/static/

    depends_on:
      - "dvd_store_web"

    networks:
      - cloudflare-net
    
    restart: unless-stopped
    
    container_name: "dvd_store_nginx"

  
  cloudflare_tunnel:
    image: cloudflare/cloudflared:1449-569a7c3c9ed0
    
    env_file: .env-vars
    
    restart: unless-stopped
    
    command: tunnel --no-autoupdate run
    
    networks:
      - cloudflare-net

    container_name: "dvd_store_cloudflare_tunnel"


volumes:
  db_dvd_store_volume:
    external: true

networks:
  cloudflare-net:
    external: true
      

