# Generated by Django 3.2.13 on 2022-09-23 20:16

from django.db import migrations
from random import randint

def copy_staff_info_to_customuser(apps, schema_editor):
    """
    copy relevant info from Staff model to CustomUser model.
    """

    # import the involved models indirectly, as it may be newer model versions than this migration expects
    CustomUser = apps.get_model("accounts_app", "CustomUser")
    Staff = apps.get_model("store_app", "Staff")

    # copy staff info to CustomUser model
    for staff in Staff.objects.all():
        CustomUser.objects.create_user(
            username=staff.first_name.lower() + staff.last_name.lower()[0] + str(randint(1, 1000)),
            email=staff.first_name.lower() + "." + staff.last_name.lower() + "@dvdstore.com",
            first_name=staff.first_name.capitalize(),
            last_name=staff.last_name.capitalize(),
            is_staff=True, # staff can access the admin site
            is_active=True,
            password="unodostres",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('store_app', '0001_initial_and_workaround_foreign_key_bug'),
    ]

    operations = [
        migrations.RunPython(copy_staff_info_to_customuser)
    ]
