# Generated by Django 3.2.13 on 2022-09-23 20:54

from django.db import migrations
from random import choice, randint


def copy_customer_info_to_customuser(apps, schema_editor):
    """
    copy relevant info from Customer model to CustomUser model.
    """

    # import the involved models indirectly, as it may be newer model versions than this migration expects
    CustomUser = apps.get_model("accounts_app", "CustomUser")
    Customer = apps.get_model("store_app", "Customer")

    # copy customer info to CustomUser model
    for customer in Customer.objects.all():
        CustomUser.objects.create_user(
            username=customer.first_name.lower() + customer.last_name[0].lower() + str(randint(1, 1000)),
            email=customer.first_name.lower() + "." + customer.last_name.lower() +
                  choice(["@myemail.com", "@itsemail.com", "@youremail.com"]),
            first_name=customer.first_name.capitalize(),
            last_name=customer.last_name.capitalize(),
            is_staff=False, # customers can't access the admin site
            is_active=True,
            password="unodostres",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_copy_staff_info'),
        ('store_app', '0001_initial_and_workaround_foreign_key_bug'),
    ]

    operations = [
        migrations.RunPython(copy_customer_info_to_customuser)
    ]
