# Generated by Django 3.2.13 on 2022-12-15 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_copy_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
