# Generated by Django 3.2.13 on 2022-12-15 15:30
import uuid

from django.db import migrations


def populate_user_uuid_field(apps, schema_editor):

    CustomUser = apps.get_model("accounts_app", "CustomUser")

    for user in CustomUser.objects.all():
        user.user_uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_add_user_uuid_field_to_customuser_model'),
    ]

    operations = [
        migrations.RunPython(populate_user_uuid_field, reverse_code=migrations.RunPython.noop),
    ]
