# Generated by Django 3.2.13 on 2022-10-17 21:27

from django.db import migrations, models
import django.db.models.deletion


"""
This migration was done following a workaround for a bug from migrations done on models generated by inspectdb command, 
in which foreign keys are not included in the migration files.

More about this bug and its workaround in:

https://code.djangoproject.com/ticket/29177
https://stackoverflow.com/questions/63501739/django-keeps-recreating-foreign-key-field-for-legacy-database-with-migrations-co
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies_app', '0001_initial_and_workaround_foreign_key_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'address',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Addresses",
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'country',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Countries",
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.address')),
            ],
            options={
                'db_table': 'customer',
                'managed': False, # this must be set to True to make tests work
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.film')),
            ],
            options={
                'db_table': 'inventory',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Inventory",
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('picture', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField()),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=40, null=True)),
                ('last_update', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.address')),
            ],
            options={
                'db_table': 'staff',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Staff",
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.address')),
                ('manager_staff', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='in_charge_of_store', to='store_app.staff')),
            ],
            options={
                'db_table': 'store',
                'managed': False, # this must be set to True to make tests work
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managed_by', to='store_app.store'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.inventory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.staff')),
            ],
            options={
                'db_table': 'rental',
                'managed': False, # this must be set to True to make tests work
                'unique_together': {('rental_date', 'inventory', 'customer')},
                'verbose_name_plural': "Rentals",
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.customer')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='store_app.rental')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.staff')),
            ],
            options={
                'db_table': 'payment',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Payments",
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.store'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.country')),
            ],
            options={
                'db_table': 'city',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Cities",
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store_app.city'),
        ),
    ]
