# Generated by Django 3.2.13 on 2022-10-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_manage_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
