# Generated by Django 3.2.13 on 2022-10-18 00:57

from django.db import migrations


def populate_staff_personal_info(apps, schema_editor):
    """
    Link Staff model with CustomUser model.

    Comparing emails is one way to assure that model entries are linked correctly.
    """

    CustomUser = apps.get_model("accounts_app", "CustomUser")
    Staff = apps.get_model("store_app", "Staff")

    # iterate over all staff entries
    for staff in Staff.objects.all():
        staff_email = staff.email.lower().split("@")[0] # get the first part of the email (before the @)
        for custom_staff in CustomUser.objects.filter(is_staff=True): # iterate over staff in CustomUser model
            custom_staff_email = custom_staff.email.split("@")[0] # get the first part of the email (before the @)
            if staff_email == custom_staff_email: # if the emails match
                staff.personal_info = custom_staff # link the two entries
                staff.save() # save entry back to the database
                break


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_add_personal_info_field'),
        ('accounts_app', '0003_copy_customer_info')
    ]

    operations = [
        migrations.RunPython(populate_staff_personal_info, reverse_code=migrations.RunPython.noop),
    ]
