# Generated by Django 3.2.13 on 2022-10-18 15:55

from django.db import migrations, models

"""
NOTE: some of the modifications proposed in this migration 
weren't applied fully by Django. So, manual modifications on the database
were necessary. To know what must change use the command sqlmigrate of manage.py
"""

class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_populate_customer_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='staff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager_staff',
            field=models.IntegerField(),
        ),
    ]
