# Generated by Django 3.2.13 on 2022-10-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_change_primary_keys_in_staff_and_customer_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='customer_old',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='staff',
            new_name='staff_old',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='customer',
            new_name='customer_old',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='staff',
            new_name='staff_old',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='manager_staff',
            new_name='manager_staff_old',
        ),
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together={('rental_date', 'inventory', 'customer_old')},
        ),
    ]
