# Generated by Django 3.2.13 on 2022-10-18 20:10

from django.db import migrations


def populate_staff_foreign_keys(apps, schema_editor):

    Rental = apps.get_model("store_app", "Rental")
    Payment = apps.get_model("store_app", "Payment")
    Store = apps.get_model("store_app", "Store")
    Staff = apps.get_model("store_app", "Staff")

    # update foreign key to staff model
    for rental in Rental.objects.all():
        staff = Staff.objects.get(staff_id=rental.staff_old)
        rental.staff = staff
        rental.save()

    # update foreign key to staff model
    for payment in Payment.objects.all():
        staff = Staff.objects.get(staff_id=payment.staff_old)
        payment.staff = staff
        payment.save()

    # update foreign key to staff model
    for store in Store.objects.all():
        staff = Staff.objects.get(staff_id=store.manager_staff_old)
        store.manager_staff = staff
        store.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_add_new_foreign_keys'),
    ]

    operations = [
        migrations.RunPython(populate_staff_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
