# Generated by Django 3.2.13 on 2022-12-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_change_film_field_in_inventory_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='film',
            new_name='film_old',
        ),
    ]
