# Generated by Django 3.2.13 on 2022-12-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0023_rename_field_in_filmactor_model'),
        ('store_app', '0016_rename_film_inventory_film_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movies_app.film'),
        ),
    ]
