# Generated by Django 3.2.13 on 2022-12-12 19:15

from django.db import migrations


def populate_film_field(apps, schema_editor):

    Inventory = apps.get_model("store_app", "Inventory")
    Film = apps.get_model("movies_app", "Film")

    for inventory in Inventory.objects.all():
        inventory.film = Film.objects.get(film_id=inventory.film_old)
        inventory.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_add_foreign_key_to_inventory_model'),
    ]

    operations = [
        migrations.RunPython(populate_film_field, reverse_code=migrations.RunPython.noop),
    ]
