# Generated by Django 3.2.13 on 2022-12-12 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0023_rename_field_in_filmactor_model'),
        ('store_app', '0018_populate_film_field_in_inventory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='film_old',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.film'),
        ),
    ]
