# Generated by Django 3.2.13 on 2022-12-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0019_remove_film_old_field_from_inventory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
