# Generated by Django 3.2.13 on 2023-01-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0020_add_available_field_to_inventory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
    ]
