# Generated by Django 3.2.13 on 2023-01-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0021_remove_address_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('address', 'city')},
        ),
    ]
