# Generated by Django 3.2.13 on 2023-01-17 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0023_store_and_address_fields_are_null_in_customer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
