# Generated by Django 3.2.13 on 2023-01-29 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_app', '0025_cascade_all_foreign_keys_movies_app'),
        ('store_app', '0024_alter_customer_personal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.store'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.film'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.rental'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.staff'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.inventory'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_by', to='store_app.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager_staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_charge_of_store', to='store_app.staff'),
        ),
    ]
