# Generated by Django 3.2.13 on 2022-10-17 21:17

from django.db import migrations, models
import django.db.models.deletion

"""
This migration was done following a workaround for a bug from migrations done on models generated by inspectdb command, 
in which foreign keys are not included in the migration files.

More about this bug and its workaround in:

https://code.djangoproject.com/ticket/29177
https://stackoverflow.com/questions/63501739/django-keeps-recreating-foreign-key-field-for-legacy-database-with-migrations-co
"""

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'actor',
                'managed': False, # this must be set to True to make tests work
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'category',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Categories",
            },
        ),
        migrations.CreateModel(
            name='FilmText',
            fields=[
                ('film_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'film_text',
                'managed': False, # this must be set to True to make tests work
                'verbose_name_plural': "Film Texts",
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'language',
                'managed': False, # this must be set to True to make tests work
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.TextField(blank=True, null=True)),
                ('rental_duration', models.PositiveIntegerField()),
                ('rental_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('special_features', models.CharField(blank=True, max_length=54, null=True)),
                ('last_update', models.DateTimeField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='films_available_in_this_language', to='movies_app.language')),
                ('original_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='films_originally_in_this_language', to='movies_app.language')),
            ],
            options={
                'db_table': 'film',
                'managed': False, # this must be set to True to make tests work
            },
        ),
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='movies_app.film')),
                ('last_update', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.category')),
            ],
            options={
                'db_table': 'film_category',
                'managed': False, # this must be set to True to make tests work
                'unique_together': {('film', 'category')},
                'verbose_name_plural': "Film Categories",
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='movies_app.actor')),
                ('last_update', models.DateTimeField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.film')),
            ],
            options={
                'db_table': 'film_actor',
                'managed': False, # this must be set to True to make tests work
                'unique_together': {('actor', 'film')},
                'verbose_name_plural': "Film Actors",
            },
        ),
    ]
