# Generated by Django 3.2.13 on 2022-10-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial_and_workaround_foreign_key_bug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filmactor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filmcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='filmtext',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': True},
        ),
    ]
