# Generated by Django 3.2.13 on 2022-10-24 19:33

from django.db import migrations


def capitalize_film_titles(apps, schema_editor):
    """
    Capitalize film titles.
    """

    def capitalize_title(title):
        words = title.split(" ")  # get each word in the title
        for i in range(len(words)):  # capitalize each word
            words[i] = words[i].capitalize()

        return " ".join(words)  # return capitalized title

    Film = apps.get_model("movies_app", "Film")
    FilmText = apps.get_model("movies_app", "FilmText")

    # iterate over all films in the database
    for film in Film.objects.all():
        film.title = capitalize_title(film.title) # capitalize their titles
        film.save() # store in the database

    # iterate over all film_text in the database
    for film_text in FilmText.objects.all():
        film_text.title = capitalize_title(film_text.title) # capitalize their titles
        film_text.save() # store in the database


def capitalize_actor_names(apps, schema_editor):
    """
    Capitalize actor names.
    """

    Actor = apps.get_model("movies_app", "Actor")

    # iterate over all actors in the database
    for actor in Actor.objects.all():
        actor.first_name = actor.first_name.capitalize() # capitalize first name
        actor.last_name = actor.last_name.capitalize() # capitalize last name
        actor.save() # store in the database


class Migration(migrations.Migration):
    dependencies = [
        ('movies_app', '0002_manage_models'),
    ]

    operations = [
        migrations.RunPython(capitalize_film_titles, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(capitalize_actor_names, reverse_code=migrations.RunPython.noop),
    ]
