# Generated by Django 3.2.13 on 2022-12-06 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_add_uuid_field_to_actor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
