# Generated by Django 3.2.13 on 2022-12-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_change_primary_key_of_actor_model'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='filmactor',
        #     name='actor_new',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movies_app.actor'),
        # ),
        migrations.AlterUniqueTogether(
            name='filmactor',
            unique_together=set(),
        ),
    ]
