# Generated by Django 3.2.13 on 2022-12-06 23:42

from django.db import migrations, models
import django.db.models.deletion


def populate_actor_new_field(apps, schema_editor):

    Actor = apps.get_model("movies_app", "Actor")
    FilmActor = apps.get_model("movies_app", "FilmActor")

    # iterate over Actor and FilmActor model entries
    for actor in Actor.objects.all():
        for film_actor in FilmActor.objects.all():
            if film_actor.actor == actor.actor_id: # if ids are the same
                film_actor.actor_new = actor # update actor_new field
                film_actor.save()
                print(f"{film_actor.actor_new.actor_uuid}, {actor.actor_uuid}")


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_remove_unique_together_constrain_in_film_actor_model'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='filmactor',
        #     name='actor_new',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='movies_app.actor'),
        # ),
        migrations.RunPython(populate_actor_new_field, reverse_code=migrations.RunPython.noop),
    ]
