# Generated by Django 3.2.13 on 2022-12-11 16:37

from django.db import migrations, models
import uuid


def populate_film_uuid(apps, schema_editor):

    Film = apps.get_model("movies_app", "Film")

    # populate actor_uuid field
    for film in Film.objects.all():
        film.film_uuid = uuid.uuid4()
        film.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_create_and_populate_actor_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # populate film_uuid field
        migrations.RunPython(populate_film_uuid, reverse_code=migrations.RunPython.noop),

        # then change null field to false, to prevent new null entries in the database
        migrations.AlterField(
            model_name='film',
            name='film_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=False, unique=True),
        ),

    ]
