# Generated by Django 3.2.13 on 2022-12-11 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0011_change_film_field_in_filmcategory_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='film_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
