# Generated by Django 3.2.13 on 2022-12-11 18:57

from django.db import migrations


def populate_film_field(apps, schema_editor):

    Film = apps.get_model("movies_app", "Film")
    FilmCategory = apps.get_model("movies_app", "FilmCategory")

    for film_category in FilmCategory.objects.all():
        film_category.film = Film.objects.get(film_id=film_category.film_old)
        film_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0014_add_foreign_keys_to_filmactor_and_filmcategory_models'),
    ]

    operations = [
        migrations.RunPython(populate_film_field, reverse_code=migrations.RunPython.noop),
    ]
