# Generated by Django 3.2.13 on 2022-12-11 20:23

from django.db import migrations

"""
This migration had to be faked (using --fake option of migrate command) and done manually in phpmyadmin
"""

class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0017_change_foreign_key_in_film_category_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmcategory',
            unique_together={('film', 'category')},
        ),
    ]
