# Generated by Django 3.2.13 on 2022-12-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0018_alter_filmcategory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcategory',
            name='film_old',
        ),
    ]
