# Generated by Django 3.2.13 on 2022-12-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0019_remove_filmcategory_film_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmactor',
            name='actor_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.actor'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.film'),
        ),
    ]
