# Generated by Django 3.2.13 on 2022-12-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0020_remove_null_from_actor_new_and_film_fields_of_filmactor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='actor_new',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='movies_app.actor'),
        ),
        migrations.AlterUniqueTogether(
            name='filmactor',
            unique_together={('actor_new', 'film')},
        ),
    ]
