# Generated by Django 3.2.13 on 2022-12-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0021_change_primary_key_in_filmactor_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmactor',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='filmactor',
            name='film_old',
        ),
    ]
