# Generated by Django 3.2.13 on 2022-12-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0023_rename_field_in_filmactor_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='film_id',
        ),
    ]
