# Generated by Django 3.2.13 on 2023-01-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0024_remove_unnecessary_fields_from_film_and_actor_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films_available_in_this_language', to='movies_app.language'),
        ),
        migrations.AlterField(
            model_name='film',
            name='original_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='films_originally_in_this_language', to='movies_app.language'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies_app.actor'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.film'),
        ),
        migrations.AlterField(
            model_name='filmcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.category'),
        ),
        migrations.AlterField(
            model_name='filmcategory',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies_app.film'),
        ),
    ]
